-- Published grain: one row per source charge row (item x setting x payer/plan), all hospitals.
-- CSV tall: one row per data record. JSON: one row per payers_information entry (or one no_payer row).
-- negotiated_rate is the dollar price when the source gives one; rate_basis says where it came from (CP-DEC 006).
select
    c.charge_id,
    c.item_id,
    c.hospital_id,
    f.hospital_name,
    f.last_updated_on as source_last_updated_on,
    c.source_sha256,
    c.source_locator,
    c.description,
    c.setting,
    c.billing_class,
    c.modifiers,
    c.drug_unit_of_measurement,
    c.drug_type_of_measurement,
    c.gross_charge,
    c.discounted_cash,
    c.payer_name,
    c.plan_name,
    c.methodology,
    c.negotiated_rate,
    c.rate_basis,
    c.negotiated_dollar,
    c.negotiated_percentage,
    c.negotiated_algorithm,
    c.count_bucket,
    c.count_n,
    c.median_amount,
    c.p10_amount,
    c.p90_amount,
    c.allowed_amounts_suppressed,
    c.median_amount_raw,
    c.p10_amount_raw,
    c.p90_amount_raw,
    c.min_charge,
    c.max_charge,
    c.additional_generic_notes,
    c.additional_payer_notes,
    c.unmapped_json
from {{ ref('stg_hpt__charges') }} c
join {{ ref('stg_hpt__files') }} f using (hospital_id, source_sha256)
