"""Regenerate the committed NPI reconciliation figures (docs/results/npi-reconciliation.md) from the warehouse.

Deterministic: the same inputs (pinned below by SHA-256 / NPPES file names) always produce the same file, so a
published number can be reproduced on request (portfolio hard rule). Nothing here computes a figure; it only reads
the gated dbt marts.
"""

from __future__ import annotations

from pathlib import Path

import duckdb

THRESHOLD = 0.90
SENSITIVITY = (0.85, 0.90, 0.95)


def _table(rows: list[tuple], header: list[str]) -> str:
    def cell(v: object) -> str:
        if v is None:
            return ""
        if isinstance(v, float):
            return f"{v:.3f}"
        return str(v).replace("|", "\\|")

    lines = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    lines += ["| " + " | ".join(cell(v) for v in r) + " |" for r in rows]
    return "\n".join(lines)


def _pct(x: float | None) -> str:
    return "" if x is None else f"{100 * x:.1f}%"


def render(warehouse: Path) -> str:
    c = duckdb.connect(str(warehouse), read_only=True)
    q = lambda sql: c.sql(sql).fetchall()  # noqa: E731

    inputs = q("SELECT hospital_id, hospital_name, source_filename, left(source_sha256, 16), last_updated_on "
               "FROM stg_hpt__files ORDER BY hospital_id")
    nppes = q("SELECT source_file, kind, coverage_end, outcome FROM rpt_nppes_file_log "
              "WHERE outcome IN ('applied', 'superseded_by_full') "
              "QUALIFY row_number() OVER (PARTITION BY source_file ORDER BY seq) = 1 ORDER BY coverage_end, source_file")
    summary = q("SELECT hospital_id, disclosed_npis, unresolved_npis, verified_npis, undisclosed_candidates, "
                "undisclosed_tier1, undisclosed_tier2, unresolved_rate, disclosure_coverage "
                "FROM rpt_npi_reconciliation ORDER BY hospital_id = 'ALL', hospital_id")
    resolution = q("SELECT hospital_id, npi, outcome, status, primary_taxonomy, nppes_name, nppes_address, "
                   "round(name_similarity, 3), address_match, check_digit_ok "
                   "FROM rpt_npi_resolution ORDER BY hospital_id, npi")
    candidates = q("SELECT hospital_id, tier, npi, org_name, primary_taxonomy, practice_address_1, "
                   "round(name_similarity, 3) FROM rpt_npi_completeness WHERE tier IN (1, 2) AND NOT disclosed "
                   "ORDER BY hospital_id, tier, npi")
    tier3 = q("SELECT hospital_id, npi, org_name, primary_taxonomy, practice_address_1, round(name_similarity, 3) "
              "FROM rpt_npi_completeness WHERE tier = 3 ORDER BY hospital_id, npi")
    sens = q("SELECT hospital_id, " + ", ".join(
        f"count(*) FILTER (WHERE NOT disclosed AND name_similarity >= {t})" for t in SENSITIVITY) +
        " FROM rpt_npi_completeness GROUP BY 1 ORDER BY 1")
    c.close()

    tot = next(r for r in summary if r[0] == "ALL")
    out = [
        "# NPI reconciliation — results",
        "",
        "> Generated by `clear-pricer report` from the gated warehouse. Do not edit by hand; re-run to reproduce.",
        "> Method and rationale: `DECISIONS.md` CP-DEC 011.",
        "",
        "## Headline",
        "",
        f"- **Unresolved-NPI rate: {_pct(tot[7])}** — {tot[2]} of {tot[1]} Type 2 NPIs disclosed in the price files "
        "do not resolve to a provider in NPPES.",
        f"- **Verified: {tot[3]} of {tot[1]}** — active, Type 2, hospital taxonomy (27x/28x), name match "
        f"≥ {THRESHOLD:.2f}, same campus.",
        f"- **Disclosure coverage: {_pct(tot[8])}** — the files disclose {tot[1]} NPIs; NPPES holds "
        f"{tot[4]} more active hospital-taxonomy NPIs registered under the same hospital names at the same "
        "addresses or campus ZIPs. These are *candidates*: NPPES registrations are rarely retired, so some may be "
        "stale or billing-only; each is listed below with its evidence.",
        "",
        _table([(r[0], r[1], r[2], r[3], r[4], r[5], r[6], _pct(r[7]), _pct(r[8])) for r in summary],
               ["hospital", "disclosed", "unresolved", "verified", "undisclosed candidates", "tier 1 (same address)",
                "tier 2 (same campus)", "unresolved rate", "disclosure coverage"]),
        "",
        "## Inputs (pinned)",
        "",
        _table(inputs, ["hospital", "name in file", "price file", "sha256 (first 16)", "file last_updated_on"]),
        "",
        _table(nppes, ["NPPES file", "kind", "coverage end", "outcome"]),
        "",
        "## Direction 1 — disclosed NPIs resolved against NPPES",
        "",
        _table(resolution, ["hospital", "npi", "outcome", "status", "primary taxonomy", "NPPES name",
                            "NPPES practice address", "name similarity", "address match", "check digit ok"]),
        "",
        "## Direction 2 — undisclosed candidates (tiers 1–2, counted)",
        "",
        _table(candidates, ["hospital", "tier", "npi", "NPPES name", "primary taxonomy", "practice address",
                            "name similarity"]),
        "",
        "## Tier 3 — same address, different name (not counted)",
        "",
        _table(tier3, ["hospital", "npi", "NPPES name", "primary taxonomy", "practice address", "name similarity"]),
        "",
        "## Threshold sensitivity",
        "",
        "Undisclosed candidates at other name-similarity thresholds (same campus ZIP, active, Type 2, hospital "
        f"taxonomy). The published figure uses {THRESHOLD:.2f}, fixed before the results were seen.",
        "",
        _table(sens, ["hospital"] + [f"≥ {t:.2f}" for t in SENSITIVITY]),
        "",
    ]
    return "\n".join(out)


def render_fhir(warehouse: Path) -> str:
    c = duckdb.connect(str(warehouse), read_only=True)
    q = lambda sql: c.sql(sql).fetchall()  # noqa: E731

    run = q("SELECT synthea_version, left(jar_sha256, 16), args, bundles, resources FROM stg_fhir__run")
    summary = q("SELECT resource_type, resources, modelled, leaf_paths, mapped_paths, mapped_value_share, "
                "structural_issues FROM rpt_fhir_summary ORDER BY resources DESC, resource_type")
    gates = q("""SELECT
        (SELECT count(*) FROM stg_fhir__patients),
        (SELECT count(*) FROM stg_fhir__patients WHERE has_synthea_identifier AND ssn_in_999_range IS NOT FALSE
                                                   AND names_digit_suffixed),
        (SELECT count(*) FROM stg_fhir__resources),
        (SELECT count(*) FROM stg_fhir__issues)""")[0]
    unmapped = q("""SELECT resource_type, path, occurrences FROM rpt_fhir_mapping
                    WHERE modelled_type AND NOT mapped
                    QUALIFY row_number() OVER (PARTITION BY resource_type ORDER BY occurrences DESC, path) <= 3
                    ORDER BY resource_type, occurrences DESC, path""")
    bridge = q("SELECT code_system, claim_lines, distinct_codes, lines_with_a_price_file_code, "
               "codes_with_a_price_file_code, hospitals_with_those_codes FROM rpt_fhir_code_bridge "
               "ORDER BY claim_lines DESC, code_system")
    c.close()

    if not run:
        return "# FHIR mapping report\n\nNo Synthea population staged. Run `clear-pricer synthea-generate` first.\n"
    version, jar, args, bundles, resources = run[0]
    patients, synthetic, total_resources, issues = gates
    modelled = [r for r in summary if r[2]]
    return "\n".join([
        "# FHIR mapping report — synthetic Synthea R4",
        "",
        "> Generated by `clear-pricer report` from the gated warehouse. Do not edit by hand; re-run to reproduce.",
        "> Method and rationale: `DECISIONS.md` CP-DEC 012. **All data is synthetic (Synthea); no PHI, by construction.**",
        "",
        "## Population (pinned)",
        "",
        f"- Synthea `{version}` (jar sha256 `{jar}…`), args: `{args}`",
        f"- {bundles} bundles, {resources:,} resources",
        "",
        "## Gates",
        "",
        f"- **Synthetic by construction:** {synthetic} of {patients} patients carry every Synthea marker "
        "(identifier system, 999-range SSN, digit-suffixed names).",
        f"- **Structural issues:** {issues} across {total_resources:,} resources (R4 1..1 elements used, coding "
        "system+code, date formats). Every reference resolves (bundle URNs, conditional identifiers, contained).",
        "",
        "## Coverage by resource type",
        "",
        f"{len(modelled)} of {len(summary)} resource types are modelled; *mapped* = leaf values the parser actually "
        "read (measured by read-tracking, not declared).",
        "",
        _table([(r[0], f"{r[1]:,}", "yes" if r[2] else "no", r[3], r[4], _pct(r[5]), r[6]) for r in summary],
               ["resource type", "resources", "modelled", "leaf paths", "mapped paths", "mapped value share",
                "structural issues"]),
        "",
        "## Largest unmapped paths (modelled types, top 3 each)",
        "",
        _table([(r[0], f"`{r[1]}`", f"{r[2]:,}") for r in unmapped], ["resource type", "path", "occurrences"]),
        "",
        "## Code bridge: synthetic claims vs real price files",
        "",
        "A synthetic claim line can be priced against a real hospital file only where both use the same code system.",
        "",
        _table([(r[0], f"{r[1]:,}", r[2], r[3], r[4], r[5]) for r in bridge],
               ["claim-line code system", "lines", "distinct codes", "lines with a price-file code",
                "codes with a price-file code", "hospitals"]),
        "",
    ])


def write(warehouse: Path, target: Path) -> Path:
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render(warehouse), encoding="utf-8", newline="\n")
    (target.parent / "fhir-mapping.md").write_text(render_fhir(warehouse), encoding="utf-8", newline="\n")
    return target
